<a href="https://colab.research.google.com/github/sanskar-decoder/Beardo-website/blob/main/logistc_multiple_regression_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Generate Dataset


In [3]:
from sklearn.datasets import make_classification

In [9]:
X,y=make_classification(n_samples=1000,n_features=20,n_informative=3,n_classes=3,random_state=42)

# Train Test Split

In [14]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.32,random_state=45)

In [18]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((680, 20), (320, 20), (680,), (320,))

**Create Model**
--

In [41]:
from sklearn.linear_model import LogisticRegression

reg=LogisticRegression(multi_class='ovr')

In [42]:
reg.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [43]:
Y_pred=reg.predict(X_test)

Y_pred is predicted output

y_test is actual output

In [44]:
Y_pred

array([1, 1, 2, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 2, 1, 1, 0, 2, 0, 2, 0, 2,
       1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 2, 0, 2, 1, 1,
       1, 2, 0, 1, 0, 2, 2, 2, 2, 1, 1, 2, 0, 2, 2, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 2, 1, 2, 1, 0, 0, 2, 2, 2, 2, 1, 0, 1, 2, 2, 0, 0, 0, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0,
       2, 0, 1, 2, 0, 2, 2, 1, 0, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0,
       0, 0, 1, 0, 2, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 1, 1, 0,
       0, 0, 0, 2, 2, 0, 2, 2, 2, 2, 1, 1, 0, 2, 0, 0, 2, 2, 2, 0, 0, 2,
       2, 1, 2, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 0, 0, 2, 1, 2, 2, 0, 2, 1, 0, 0,
       0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 1, 0, 2, 2, 1, 0, 0, 1, 2, 2,
       0, 2, 1, 2, 2, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2,
       0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 2, 0, 1, 2, 2, 0, 0, 2,
       0, 0, 0, 2, 0, 2, 1, 2, 0, 0, 0, 1, 1, 2, 2,

In [45]:
len(y_test)

320

# For Actual data value count of class
--

In [46]:
from collections import Counter
value=2
value1=1
value0=0
counter = Counter(y_test)
print("2 :",counter[value])
print("1 :",counter[value1])
print("0 :" ,counter[value0])
print(f' total size  : {counter[value1]+counter[value]+counter[value0]}')

2 : 103
1 : 116
0 : 101
 total size  : 320


# For predicted data point value count of classes

In [47]:
from collections import Counter
value=2
value1=1
value0=0
counter = Counter(Y_pred)
print("2 :",counter[value])
print("1 :",counter[value1])
print("0 :" ,counter[value0])
print(f' total size  : {counter[value1]+counter[value]+counter[value0]}')

2 : 124
1 : 55
0 : 141
 total size  : 320


# Performace Metrics without hyperparameter tunning

In [48]:

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [49]:
print(f'Accuracy score of the model is {accuracy_score(y_test,Y_pred)}')
print('Confusion Matrix : ')
print(confusion_matrix(y_test,Y_pred))

print(classification_report(y_test,Y_pred))

Accuracy score of the model is 0.65
Confusion Matrix : 
[[82 11  8]
 [54 36 26]
 [ 5  8 90]]
              precision    recall  f1-score   support

           0       0.58      0.81      0.68       101
           1       0.65      0.31      0.42       116
           2       0.73      0.87      0.79       103

    accuracy                           0.65       320
   macro avg       0.65      0.67      0.63       320
weighted avg       0.65      0.65      0.62       320



HyperParameter Tunning and cross Validation
--

In [50]:
model=LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
c_values=[100,0.1,0.01,1.0,0.001]
solvers=['lbfgs', 'liblinear','newton-cg','newton-cholesky','sag','saga']


In [54]:

params=dict(penalty=penalty,C=c_values,solver=solvers)

Stfrom ratifiedKFold
--

In [55]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

# Grid search Cv


In [52]:
from sklearn.model_selection import GridSearchCV

In [56]:
grid=GridSearchCV(estimator=model,param_grid=params,cv=cv,n_jobs=-1)


In [57]:
grid.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1169, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 0.1, 0.01, 1.0, 0.001],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']})

In [58]:
y_prdg1=grid.predict(X_test)

check for parameter what model take

In [59]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

Perfomance Matrix after hyperparameter tunning
--

In [60]:

print('accuracy',accuracy_score(y_test,y_prdg1))
print()
print(f'Confusion matrix : \n{confusion_matrix(y_test,y_prdg1)}')
print(classification_report(y_test,y_prdg1))

accuracy 0.665625

Confusion matrix : 
[[85  9  7]
 [53 35 28]
 [ 4  6 93]]
              precision    recall  f1-score   support

           0       0.60      0.84      0.70       101
           1       0.70      0.30      0.42       116
           2       0.73      0.90      0.81       103

    accuracy                           0.67       320
   macro avg       0.68      0.68      0.64       320
weighted avg       0.68      0.67      0.63       320

